language: ruby
cache: bundler

script: bundle exec rake site:deploy

notifications:
  email:
    recipients:
      - david@dmarby.se
    on_success: change
    on_failure: always
env:
  global:
    - secure: "H092qsDKX+GvdMUCWpEfSuG3dZhrFYLfC3Gv0U47h4QFlf6eyw4DTrFmCIOPsl7XJ7b2A/nv2OHMQ7i85LB445w5saow7wBMnUong/DjUbsvXwJ3bOlO0nQJa//Uz53sXIuYotuRM5O/fCIm+h8FBA7eRnGely5NsYeXQ+Lpt1g="
    - secure: "MiN2zj3latuX7Mt21hfqJTrErjBguWO+RSDmn9MrpQaSJBxZuJUDjQ29lDBXoMKrRyj5Boh3L3m0N1AmXd/rMEayHfuaFeW6qp9mR53SuEbz9m5SlmNltIcssYwu3DTBUZ69UWOkxM0yuFtHJhFH8FdjxF29cWmm57yP2ik2o5w="
# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
